//
//  UIFont+Symbolset.m
//  UIFont+Symbolset
//
//  Created by Brandon Williams on 6/3/13.
//  Copyright (c) 2013 Opetopic. All rights reserved.
//

#import "UIFont+Symbolset.h"

@implementation UIFont (Symbolset)

+(instancetype) ssStandardFontWithSize:(CGFloat)size {
  return [UIFont fontWithName:@"SSStandard" size:size];
}

+(NSString*) ssStandardSymbolForString:(NSString*)string {

  static NSDictionary *ssStandardSymbols = nil;
  if (! ssStandardSymbols) {
    ssStandardSymbols = @{
                          @"cursor": @"",
                          @"crosshair": @"⌖",
                          @"screenshot": @"⌖",
                          @"search": @"🔎",
                          @"zoom": @"",
                          @"zoomin": @"",
                          @"zoom in": @"",
                          @"zoomout": @"",
                          @"zoom out": @"",
                          @"view": @"👀",
                          @"eye": @"👀",
                          @"look": @"👀",
                          @"visible": @"👀",
                          @"visibility": @"👀",
                          @"attach": @"📎",
                          @"attachment": @"📎",
                          @"paperclip": @"📎",
                          @"link": @"🔗",
                          @"move": @"",
                          @"edit": @"✎",
                          @"write": @"✎",
                          @"pencil": @"✎",
                          @"writingdisabled": @"",
                          @"writing disabled": @"",
                          @"pencildisabled": @"",
                          @"pencil disabled": @"",
                          @"erase": @"✐",
                          @"eraser": @"✐",
                          @"compose": @"📝",
                          @"lock": @"🔒",
                          @"locked": @"🔒",
                          @"private": @"🔒",
                          @"secure": @"🔒",
                          @"unlock": @"🔓",
                          @"unlocked": @"🔓",
                          @"public": @"🔓",
                          @"insecure": @"🔓",
                          @"key": @"🔑",
                          @"backspace": @"⌫",
                          @"ban": @"🚫",
                          @"trash": @"",
                          @"trashcan": @"",
                          @"target": @"◎",
                          @"tag": @"",
                          @"tags": @"",
                          @"tagged": @"",
                          @"keyword": @"",
                          @"keywords": @"",
                          @"bookmark": @"🔖",
                          @"flag": @"⚑",
                          @"like": @"👍",
                          @"approve": @"👍",
                          @"thumbsup": @"👍",
                          @"thumbs up": @"👍",
                          @"dislike": @"👎",
                          @"disapprove": @"👎",
                          @"thumbsdown": @"👎",
                          @"thumbs down": @"👎",
                          @"heart": @"♥",
                          @"love": @"♥",
                          @"halfheart": @"",
                          @"half heart": @"",
                          @"zelda": @"",
                          @"star": @"⋆",
                          @"favorite": @"⋆",
                          @"halfstar": @"",
                          @"half star": @"",
                          @"sample": @"",
                          @"eyedropper": @"",
                          @"crop": @"",
                          @"layers": @"",
                          @"windows": @"",
                          @"fill": @"",
                          @"stroke": @"",
                          @"phone": @"📞",
                          @"call": @"📞",
                          @"telephone": @"📞",
                          @"phonedisabled": @"",
                          @"phone disabled": @"",
                          @"calldisabled": @"",
                          @"call disabled": @"",
                          @"endcall": @"",
                          @"end call": @"",
                          @"telephonedisabled": @"",
                          @"telephone disabled": @"",
                          @"rss": @"",
                          @"facetime": @"",
                          @"reply": @"↩",
                          @"send": @"",
                          @"mail": @"✉",
                          @"email": @"✉",
                          @"envelope": @"✉",
                          @"inbox": @"📥",
                          @"chat": @"💬",
                          @"comment": @"💬",
                          @"talk": @"💬",
                          @"ellipsischat": @"",
                          @"ellipsis chat": @"",
                          @"ellipsis": @"…",
                          @"user": @"👤",
                          @"avatar": @"👤",
                          @"maleavatar": @"👤",
                          @"male avatar": @"👤",
                          @"maleuser": @"👤",
                          @"male user": @"👤",
                          @"femaleuser": @"👧",
                          @"female user": @"👧",
                          @"femaleavatar": @"👧",
                          @"female avatar": @"👧",
                          @"users": @"👥",
                          @"avatars": @"👥",
                          @"cart": @"",
                          @"shoppingcart": @"",
                          @"shopping cart": @"",
                          @"creditcard": @"💳",
                          @"credit card": @"💳",
                          @"cost": @"💲",
                          @"dollarsign": @"💲",
                          @"dollar sign": @"💲",
                          @"price": @"💲",
                          @"barchart": @"📊",
                          @"bar chart": @"📊",
                          @"piechart": @"",
                          @"pie chart": @"",
                          @"box": @"📦",
                          @"package": @"📦",
                          @"home": @"⌂",
                          @"house": @"⌂",
                          @"buildings": @"🏢",
                          @"city": @"🏢",
                          @"warehouse": @"",
                          @"globe": @"🌎",
                          @"earth": @"🌎",
                          @"world": @"🌎",
                          @"navigate": @"",
                          @"navigation": @"",
                          @"locate": @"",
                          @"compass": @"",
                          @"signpost": @"",
                          @"directions": @"",
                          @"map": @"",
                          @"location": @"",
                          @"pin": @"📍",
                          @"database": @"",
                          @"harddrive": @"",
                          @"hard drive": @"",
                          @"hdd": @"",
                          @"music": @"♫",
                          @"musicnote": @"♫",
                          @"audio": @"♫",
                          @"mic": @"🎤",
                          @"microphone": @"🎤",
                          @"dictate": @"🎤",
                          @"volume": @"🔈",
                          @"sound": @"🔈",
                          @"speaker": @"🔈",
                          @"lowvolume": @"🔉",
                          @"low volume": @"🔉",
                          @"volumelow": @"🔉",
                          @"volume low": @"🔉",
                          @"highvolume": @"🔊",
                          @"high volume": @"🔊",
                          @"volumehigh": @"🔊",
                          @"volume high": @"🔊",
                          @"airplay": @"",
                          @"camera": @"📷",
                          @"picture": @"🌄",
                          @"pictures": @"🌄",
                          @"image": @"🌄",
                          @"images": @"🌄",
                          @"photo": @"🌄",
                          @"photos": @"🌄",
                          @"photograph": @"🌄",
                          @"photographs": @"🌄",
                          @"video": @"📹",
                          @"videos": @"📹",
                          @"videocamera": @"📹",
                          @"play": @"▶",
                          @"pause": @"",
                          @"stop": @"■",
                          @"record": @"●",
                          @"rewind": @"⏪",
                          @"fastforward": @"⏩",
                          @"fast forward": @"⏩",
                          @"skipback": @"⏮",
                          @"skip back": @"⏮",
                          @"skip": @"⏭",
                          @"skipforward": @"⏭",
                          @"skip forward": @"⏭",
                          @"eject": @"⏏",
                          @"repeat": @"🔁",
                          @"replay": @"↺",
                          @"rotateleft": @"↺",
                          @"rotate left": @"↺",
                          @"undo": @"↺",
                          @"shuffle": @"🔀",
                          @"book": @"📕",
                          @"openbook": @"📖",
                          @"open book": @"📖",
                          @"notebook": @"📓",
                          @"newspaper": @"📰",
                          @"news": @"📰",
                          @"grid": @"",
                          @"rows": @"",
                          @"columns": @"",
                          @"thumbnails": @"",
                          @"filter": @"",
                          @"funnel": @"",
                          @"desktop": @"💻",
                          @"computer": @"💻",
                          @"display": @"💻",
                          @"monitor": @"💻",
                          @"laptop": @"",
                          @"tablet": @"",
                          @"ipad": @"",
                          @"cell": @"📱",
                          @"cellphone": @"📱",
                          @"cell phone": @"📱",
                          @"iphone": @"📱",
                          @"mobile": @"📱",
                          @"mobilephone": @"📱",
                          @"mobile phone": @"📱",
                          @"smartphone": @"📱",
                          @"battery": @"🔋",
                          @"fullbattery": @"🔋",
                          @"full battery": @"🔋",
                          @"batteryfull": @"🔋",
                          @"battery full": @"🔋",
                          @"highbattery": @"",
                          @"high battery": @"",
                          @"batteryhigh": @"",
                          @"battery high": @"",
                          @"mediumbattery": @"",
                          @"medium battery": @"",
                          @"batterymedium": @"",
                          @"battery medium": @"",
                          @"lowbattery": @"",
                          @"low battery": @"",
                          @"batterylow": @"",
                          @"battery low": @"",
                          @"emptybattery": @"",
                          @"empty battery": @"",
                          @"batteryempty": @"",
                          @"battery empty": @"",
                          @"lightbulb": @"💡",
                          @"idea": @"💡",
                          @"downloadcloud": @"",
                          @"download cloud": @"",
                          @"clouddownload": @"",
                          @"cloud download": @"",
                          @"download": @"",
                          @"uploadcloud": @"",
                          @"upload cloud": @"",
                          @"cloudupload": @"",
                          @"cloud upload": @"",
                          @"upload": @"",
                          @"fork": @"",
                          @"merge": @"",
                          @"transfer": @"⇆",
                          @"refresh": @"↻",
                          @"redo": @"↻",
                          @"rotateright": @"↻",
                          @"rotate right": @"↻",
                          @"sync": @"",
                          @"syncing": @"",
                          @"loading": @"",
                          @"wifi": @"",
                          @"connection": @"",
                          @"nodes": @"",
                          @"file": @"📄",
                          @"document": @"📄",
                          @"page": @"📄",
                          @"folder": @"📁",
                          @"quote": @"“",
                          @"pullquote": @"“",
                          @"pull quote": @"“",
                          @"text": @"",
                          @"font": @"",
                          @"typeface": @"",
                          @"print": @"⎙",
                          @"printer": @"⎙",
                          @"fax": @"📠",
                          @"list": @"",
                          @"layout": @"",
                          @"action": @"",
                          @"out": @"",
                          @"share": @"",
                          @"visit": @"",
                          @"redirect": @"↪",
                          @"expand": @"⤢",
                          @"contract": @"",
                          @"help": @"❓",
                          @"question": @"❓",
                          @"info": @"ℹ",
                          @"information": @"ℹ",
                          @"alert": @"⚠",
                          @"warning": @"⚠",
                          @"caution": @"⛔",
                          @"exit": @"",
                          @"logout": @"",
                          @"log out": @"",
                          @"signout": @"",
                          @"sign out": @"",
                          @"plus": @"+",
                          @"add": @"+",
                          @"hyphen": @"-",
                          @"minus": @"-",
                          @"remove": @"-",
                          @"subtract": @"-",
                          @"check": @"✓",
                          @"checked": @"✓",
                          @"checkmark": @"✓",
                          @"delete": @"␡",
                          @"close": @"␡",
                          @"settings": @"⚙",
                          @"cog": @"⚙",
                          @"gear": @"⚙",
                          @"dashboard": @"",
                          @"notification": @"🔔",
                          @"notifications": @"🔔",
                          @"bell": @"🔔",
                          @"notificationsdisabled": @"🔕",
                          @"notifications disabled": @"🔕",
                          @"notificationdisabled": @"🔕",
                          @"notification disabled": @"🔕",
                          @"belldisabled": @"🔕",
                          @"bell disabled": @"🔕",
                          @"clock": @"⏲",
                          @"time": @"⏲",
                          @"stopwatch": @"⏱",
                          @"timer": @"⏱",
                          @"calendar": @"📅",
                          @"date": @"📅",
                          @"addcalendar": @"",
                          @"add calendar": @"",
                          @"adddate": @"",
                          @"add date": @"",
                          @"calendaradd": @"",
                          @"calendar add": @"",
                          @"removecalendar": @"",
                          @"remove calendar": @"",
                          @"removedate": @"",
                          @"remove date": @"",
                          @"calendarremove": @"",
                          @"calendar remove": @"",
                          @"checkcalendar": @"",
                          @"check calendar": @"",
                          @"checkdate": @"",
                          @"check date": @"",
                          @"calendarcheck": @"",
                          @"calendar check": @"",
                          @"deletecalendar": @"",
                          @"delete calendar": @"",
                          @"deletedate": @"",
                          @"delete date": @"",
                          @"calendardelete": @"",
                          @"calendar delete": @"",
                          @"briefcase": @"💼",
                          @"work": @"💼",
                          @"cloud": @"☁",
                          @"drop": @"💧",
                          @"droplet": @"💧",
                          @"flask": @"",
                          @"up": @"⬆",
                          @"upright": @"⬈",
                          @"up right": @"⬈",
                          @"right": @"➡",
                          @"forward": @"➡",
                          @"downright": @"⬊",
                          @"down right": @"⬊",
                          @"down": @"⬇",
                          @"downleft": @"⬋",
                          @"down left": @"⬋",
                          @"left": @"⬅",
                          @"back": @"⬅",
                          @"upleft": @"⬉",
                          @"up left": @"⬉",
                          @"navigateup": @"",
                          @"navigate up": @"",
                          @"navigateright": @"▻",
                          @"navigate right": @"▻",
                          @"next": @"▻",
                          @"navigatedown": @"",
                          @"navigate down": @"",
                          @"navigateleft": @"◅",
                          @"navigate left": @"◅",
                          @"previous": @"◅",
                          @"ascend": @"▴",
                          @"ascending": @"▴",
                          @"directup": @"▴",
                          @"direct up": @"▴",
                          @"directright": @"▹",
                          @"direct right": @"▹",
                          @"descend": @"▾",
                          @"descending": @"▾",
                          @"directdown": @"▾",
                          @"direct down": @"▾",
                          @"dropdown": @"▾",
                          @"directleft": @"◃",
                          @"direct left": @"◃",
                          @"retweet": @""
                          };
  }
  return ssStandardSymbols[string] ?: string;
}

+(instancetype) ssSocialFontWithSize:(CGFloat)size {
  return [UIFont fontWithName:@"SSSocialRegular" size:size];
}

+(NSString*) ssSocialSymbolForString:(NSString*)string {

  static NSDictionary *ssSocialSymbols = nil;
  if (! ssSocialSymbols) {
    ssSocialSymbols = @{@"facebook": @"",
                        @"twitter": @"",
                        @"linkedin": @"",
                        @"google+": @"",
                        @"google +": @"",
                        @"googleplus": @"",
                        @"google plus": @"",
                        @"tumblr": @"",
                        @"wordpress": @"",
                        @"blogger": @"",
                        @"posterous": @"",
                        @"youtube": @"",
                        @"vimeo": @"",
                        @"flickr": @"",
                        @"instagram": @"",
                        @"pinterest": @"",
                        @"svpply": @"",
                        @"readmill": @"",
                        @"dropbox": @"",
                        @"dribbble": @"",
                        @"behance": @"",
                        @"github": @"",
                        @"githuboctocat": @"",
                        @"github octocat": @"",
                        @"octocat": @"",
                        @"stackoverflow": @"",
                        @"stack overflow": @"",
                        @"paypal": @"",
                        @"kickstarter": @"",
                        @"foursquare": @"",
                        @"skype": @"",
                        @"rdio": @"",
                        @"spotify": @"",
                        @"lastfm": @"",
                        @"last fm": @"",
                        @"email": @"✉",
                        @"envelope": @"✉",
                        @"mail": @"✉",
                        @"approve": @"👍",
                        @"like": @"👍",
                        @"thumbsup": @"👍",
                        @"thumbs up": @"👍",
                        @"rss": @""
                        };
  }
  return ssSocialSymbols[string] ?: string;
}

+(instancetype) ssSocialCircleFontWithSize:(CGFloat)size {
  return [UIFont fontWithName:@"SSSocialCircle" size:size];
}

+(NSString*) ssSocialSymbolCircleForString:(NSString*)string {

  static NSDictionary *ssSocialCircleSymbols = nil;
  if (! ssSocialCircleSymbols) {
    ssSocialCircleSymbols = @{@"facebook": @"",
                              @"twitter": @"",
                              @"linkedin": @"",
                              @"google+": @"",
                              @"google +": @"",
                              @"googleplus": @"",
                              @"google plus": @"",
                              @"tumblr": @"",
                              @"wordpress": @"",
                              @"blogger": @"",
                              @"posterous": @"",
                              @"youtube": @"",
                              @"vimeo": @"",
                              @"flickr": @"",
                              @"instagram": @"",
                              @"pinterest": @"",
                              @"svpply": @"",
                              @"readmill": @"",
                              @"dropbox": @"",
                              @"dribbble": @"",
                              @"behance": @"",
                              @"github": @"",
                              @"githuboctocat": @"",
                              @"github octocat": @"",
                              @"octocat": @"",
                              @"stackoverflow": @"",
                              @"stack overflow": @"",
                              @"paypal": @"",
                              @"kickstarter": @"",
                              @"foursquare": @"",
                              @"skype": @"",
                              @"rdio": @"",
                              @"spotify": @"",
                              @"lastfm": @"",
                              @"last fm": @"",
                              @"email": @"✉",
                              @"envelope": @"✉",
                              @"mail": @"✉",
                              @"approve": @"👍",
                              @"like": @"👍",
                              @"thumbsup": @"👍",
                              @"thumbs up": @"👍",
                              @"rss": @""
                              };
  }
  return ssSocialCircleSymbols[string] ?: string;
}

@end
